#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [634313355, 1754736684, 1208666837, 459420149, 330752661, 1300036106, 798801343, 561641333];
