#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1472706656, 209834704, 1376050866, 7041963, 126724650, 1226536864, 907966835, 635432348];
