#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [228900133, 181842167, 1146450027, 1656936424, 750658256, 235617608, 302922418, 255459766];
