#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1093799118, 1796879849, 1657596138, 1446912981, 18538717, 1827837341, 673172124, 1713388083];
