#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1982856507, 1360835876, 1032304188, 1744444400, 606944830, 1748523552, 1684302849, 1265208047];
