#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1109526339, 166958634, 439014057, 845844512, 704285449, 690050234, 999486565, 1515374278];
