#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1580128860, 291404282, 1055460489, 1414572901, 293108667, 900963533, 1670643010, 1649117249];
