#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1997710199, 1960324129, 291310246, 1295267809, 1433444556, 1415629931, 1529070477, 1969225635];
