#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1067683389, 1347850975, 162845521, 469919287, 1156023803, 1345016190, 1047125935, 636158532];
