#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [260608041, 1950752858, 1547853114, 1785903936, 1539727954, 704118120, 1884083968, 1603550460];
