#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [84306319, 1663458145, 538651173, 1435231011, 1748209700, 1483017013, 1514214160, 1071159471];
