#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1708973983, 1216918399, 1988105208, 1859667429, 883245521, 498578010, 1121688591, 209023330];
