#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [392015361, 317783303, 675078434, 863885872, 267995989, 1325851029, 1158031060, 1530485617];
